name: Workflow 1
on: push

jobs:
  requisites-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install NodeJS dependencies
        run: npm ci
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Lint code
        run: |
            echo "Linting code"
            npm lint
  test-job:
    needs: lint-job
    runs-on: ubuntu-latest
    steps:
      - name: Test code
        run : |
            echo "Testing code"
            npm test
  build-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Build code
        run: |
            echo "Building code"
            npm run build