name: Workflow 1
on: push

jobs:
  requisites-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS dependencies
        run: npm ci
  lint-job:
    needs: requisites-job
    runs-on: ubuntu-latest
    steps:
      - name: Lint code
        run: |
            echo "Linting code"
            npm run lint
  test-job:
    needs: lint-job
    runs-on: ubuntu-latest
    steps:
      - name: Test code
        run : |
            echo "Testing code"
            npm run test
  build-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Build code
        run: |
            echo "Building code"
            npm run build